### PR TITLE
Add a way for simple type names to allow inheritance for subclasses

### PR DESCRIPTION
**Pull request by OroArmor**

### CODE REVIEW

**Comment by OroArmor** [comment]
Because I use the `InheritanceIndex` in the `SimpleTypeSingleIndex`, I wonder if the reason my tests are passing is because of the order the classes are loaded in and if the classes were loaded after the class I test against that it would fail.

**Comment by OroArmor** [comment]
> Because I use the `InheritanceIndex` in the `SimpleTypeSingleIndex`, I wonder if the reason my tests are passing is because of the order the classes are loaded in and if the classes were loaded after the class I test against that it would fail.

Wrote a test that should hit this and it seems fine. this is fully ready to go

**Review by ix0rai — APPROVED** [review]
looks good! have you checked the output on QM?

**Comment by OroArmor** [comment]
Not yet, because it doesn't currently change anything unless I enable some inheritance

**Pull request merged**
