### PR TITLE
Cleanup the constant fields name finder (renamed from enum fields)

### PR DESCRIPTION
**Pull request by IotaBread**
Now names are searched recursively, and strings passed to constructors are properly detected

### CODE REVIEW

**Review by OroArmor — CHANGES_REQUESTED** [review]
Looks like some licenses need updating

**Comment by IotaBread** [comment]
The header is set to just display the creation year, should I change it?

**Comment by OroArmor** [comment]
Not sure. I thought QSL used a range from creation to current, but not sure

**Comment by IotaBread** [comment]
[It doesn't](https://github.com/QuiltMC/quilt-standard-libraries/blob/0cb467f1079fdc44b3c37647e648e26020a82888/codeformat/HEADER#L15)

**Review by OroArmor — APPROVED** [review]

**Pull request merged**
